---
title: "Heterogeneity"
author: "Anna Langener"
date: "6/24/2020"
output: html_document
---


```{r include=FALSE}
library(lmerTest)
library(psych)
library(ggplot2)
library(kableExtra)
library(tidyverse)
library(tidyselect)
library(dplyr)
library(foreign)
library(xtable)
library(ltm)
library(flextable)
library(qgraph)
library(graphicalVAR)
library(psychonetrics)
library(lavaan)
library(semPlot)
library(tidyr)
library(ggcorrplot)
library(qwraps2)
library(lme4)
library(lmerTest)
library(nlme)
library(stargazer)

Data_combined_Base <- as.data.frame(read.csv("/Users/annalangener/Desktop/OneDrive/Masterthesis/Psychology/Data_combined_Base.csv", header = T))

variables <- c("InflationTotal_Basicneed_expenditure", "InflationTotal_Basicneed_expenditure_short", "InflationTotal_BusinessInvestment", "InflationTotal_AssetsInvestment", "InflationTotal_Investment", "InflationTotal_income_without", "InflationTotal_Food")


Bvariables <- c("InflationTotal_Basicneed_expenditure_t0", "InflationTotal_Basicneed_expenditure_short_t0", "InflationTotal_BusinessInvestment_t0", "InflationTotal_AssetsInvestment_t0", "InflationTotal_Investment_t0", "InflationTotal_income_without_t0", "InflationTotal_Food_t0")
## New Categories

```


```{r include=FALSE}
i <- 1

#### Heterogeneity
#1 Linear
fit1_het_int <- lm(as.formula(paste(variables[i]," ~ Weeknr +", Bvariables[i] ," + prodsum:Weeknr  + school2:Weeknr + howmanyHHM_1:Weeknr + insurance2:Weeknr + NoOccupation_Daylabourer:Weeknr + Farmer:Weeknr + InformalWork:Weeknr + as.factor(Cstartdate.y)")),na.action = na.omit, Data_combined_Base)

#2 Linear AR1
fit1_het_int_AR <- gls(as.formula(paste(variables[i]," ~ Weeknr +", Bvariables[i] ," + prodsum:Weeknr  + school2:Weeknr + howmanyHHM_1:Weeknr + insurance2:Weeknr + NoOccupation_Daylabourer:Weeknr + Farmer:Weeknr + InformalWork:Weeknr + as.factor(Cstartdate.y)")), correlation = corAR1(0.5,form=~1),na.action = na.omit, data = Data_combined_Base)
coef_fit1_het_int_AR <- coef(summary(fit1_het_int_AR))


#3 Clustered

fit1_test_het_int <- clubSandwich::coef_test(fit1_het_int, vcov = "CR1", cluster = Data_combined_Base$ID_NR_VU, test = "naive-t")

#4 Multi

fit1_het_ML_withoutAR_interaction <-lme(as.formula(paste(variables[i]," ~ 1 + Weeknr +", Bvariables[i] ," + prodsum:Weeknr + school2:Weeknr + howmanyHHM_1:Weeknr + insurance2:Weeknr + NoOccupation_Daylabourer:Weeknr + Farmer:Weeknr + InformalWork:Weeknr + as.factor(Cstartdate.y)")), random=~ Weeknr|ID_NR_VU, data = Data_combined_Base, method = "ML", na.action = na.omit)
#control = lmeControl(opt = "optim")

#5 Multi AR1

fit1_het_ML_het_withAR_interaction <- lme(as.formula(paste(variables[i]," ~ 1 + Weeknr +", Bvariables[i] ," + prodsum:Weeknr + school2:Weeknr + howmanyHHM_1:Weeknr + insurance2:Weeknr + NoOccupation_Daylabourer:Weeknr + Farmer:Weeknr + InformalWork:Weeknr + as.factor(Cstartdate.y)")), random=~ Weeknr|ID_NR_VU, data = Data_combined_Base, correlation=corAR1(form=  ~ Weeknr |ID_NR_VU), method = "ML", na.action = na.omit)


fit1_table3 <- invisible(stargazer(fit1_het_int,fit1_het_int, fit1_het_int_AR, fit1_het_ML_withoutAR_interaction, fit1_het_ML_het_withAR_interaction, type = "html",  se=list(NULL, fit1_test_het_int$SE, NULL,NULL,NULL), omit = "Cstartdate.y", dep.var.labels.include	= F, add.lines = list(c("Calendar Month Dummy", "Yes", "Yes", "Yes", "Yes","Yes"), c("AIC", round(AIC(fit1_het_int),1), round(AIC(fit1_het_int),1), round(AIC(fit1_het_int_AR),1), round(AIC(fit1_het_ML_withoutAR_interaction),1), round(AIC(fit1_het_ML_het_withAR_interaction),1)), c("BIC", round(BIC(fit1_het_int),1), round(BIC(fit1_het_int),1), round(BIC(fit1_het_int_AR),1), round(BIC(fit1_het_ML_withoutAR_interaction),1), round(BIC(fit1_het_ML_het_withAR_interaction),1))), omit.stat = c("all")))

# covariate.labels = c("Program Week","Baseline Value DV","Program Week:Sum Productive Assets", "Program Week: School Level", "Program Week:Household size", "Program Week:Insurance", "Program Week:No Occupation/ Day Labourer", "Program Week:Farmer","Program Week:Informal Work", "Constant")

```

Final Table

```{r echo=TRUE}

knitr::kable(fit1_table3, format = "html", escape = FALSE)


```

