---
title: "Only one"
author: "Anna Langener"
date: "6/24/2020"
output: html_document
---
---
title: "Untitled"
author: "Anna Langener"
date: "6/16/2020"
output:
  html_document: default
  word_document: default
---

Thesis Analysis Regressions


```{r include=FALSE}
library(lmerTest)
library(psych)
library(ggplot2)
library(kableExtra)
library(tidyverse)
library(tidyselect)
library(dplyr)
library(foreign)
library(xtable)
library(ltm)
library(flextable)
library(qgraph)
library(graphicalVAR)
library(psychonetrics)
library(lavaan)
library(semPlot)
library(tidyr)
library(ggcorrplot)
library(qwraps2)
library(lme4)
library(lmerTest)
library(nlme)
library(stargazer)

Data_combined_Base <- as.data.frame(read.csv("/Users/annalangener/Desktop/OneDrive/Masterthesis/Psychology/Data_combined_Base.csv", header = T))


variables <- c("InflationTotal_Basicneed_expenditure", "InflationTotal_Basicneed_expenditure_short", "InflationTotal_BusinessInvestment", "InflationTotal_AssetsInvestment", "InflationTotal_Investment", "InflationTotal_income_without", "InflationTotal_Food")


Bvariables <- c("InflationTotal_Basicneed_expenditure_t0", "InflationTotal_Basicneed_expenditure_short_t0", "InflationTotal_BusinessInvestment_t0", "InflationTotal_AssetsInvestment_t0", "InflationTotal_Investment_t0", "InflationTotal_income_without_t0", "InflationTotal_Food_t0")

```


```{r include=FALSE}
i <- 1
#1 Linear
fit1 <- lm(as.formula(paste(variables[i]," ~ Weeknr +", Bvariables[i] ,"+ as.factor(Cstartdate.y)")), Data_combined_Base)

#2 Linear AR1
fit1_AR <- gls(as.formula(paste(variables[i]," ~ Weeknr +", Bvariables[i] ,"+ as.factor(Cstartdate.y)")), Data_combined_Base, correlation = corAR1(0.5,form=~1))

#3 Clustered
fit1_test <- clubSandwich::coef_test(fit1, vcov = "CR1", cluster = Data_combined_Base$ID_NR_VU, test = "naive-t")

#4 Multi level

fit1_ML_withoutAR <-lme(as.formula(paste(variables[i]," ~ 1 + Weeknr +", Bvariables[i] ,"+ as.factor(Cstartdate.y)")), random=~ Weeknr|ID_NR_VU, data = Data_combined_Base, method = "ML", control = c(opt = "optim"))

#5 Multi level with AR1
#fit1_ML_withAR <- lme(as.formula(paste(variables[i]," ~ 1 + Weeknr +", Bvariables[i] ,"+ as.factor(Cstartdate.y)")), random=~ Weeknr |ID_NR_VU, correlation=corAR1(form=  ~ Weeknr |ID_NR_VU), 	data=Data_combined_Base, method = "ML")


fit1_table1 <- invisible(stargazer(fit1, fit1, fit1_AR,fit1_ML_withoutAR, type = "html",  se=list(NULL, fit1_test$SE, NULL,NULL,NULL), p =list(NULL, fit1_test$p_t, NULL,NULL,NULL), omit = "Cstartdate.y", dep.var.labels.include	= F, add.lines = list(c("Calendar Month Dummy", "Yes", "Yes", "Yes", "Yes","Yes"), c("AIC", round(AIC(fit1),1), round(AIC(fit1),1), round(AIC(fit1_AR),1), round(AIC(fit1_ML_withoutAR),1)), c("BIC", round(BIC(fit1),1), round(BIC(fit1),1), round(BIC(fit1_AR),1), round(BIC(fit1_ML_withoutAR),1))), covariate.labels = c("Program Week","Baseline Value DV","Constant")))

```

Final Table

```{r echo=TRUE}
knitr::kable(fit1_table1, format = "html", escape = FALSE)
```

